### ISSUE TITLE
wrong import file-name in _icon.scss_sassvg.scss

### ISSUE THREAD

**Issue by meodai** [MattDiMu/gulp-sassvg#1]
`@import "sassvg-data"`

fails to import since the file with the date is called. `_icons.scss_sassvg-data.scss` 
I think it would be fine to have to import both in the main sass file

**Comment by MattDiMu** [comment]
Thx for your feedback. I'm not sure, however, what you mean.

After running the gulp-task, you should have 2 files in the specified folder: _sassvg.scss and _sassvg-data.scss. How do you get a file named ```_icons.scss_sassvg-data.scss```?

**Comment by meodai** [comment]
@MattDiMu https://github.com/MattDiMu/gulp-sassvg/blob/master/_sassvg.scss#L30

**Comment by MattDiMu** [comment]
What's the problem with it? The file is called _sassvg-data.scss, is in the same folder and therefore imported.

**Comment by meodai** [comment]
well for some reason my file is called  `_icons.scss_sassvg-data.scss`. Maybe because i run svgmin before it. I don't know.

**Comment by MattDiMu** [comment]
That's strange, how does your gulp task look?

**Comment by MattDiMu** [comment]
@meodai your gulp task would have helped me to find the issue earlier. By chance i still managed to find the issue and fixed it in Version 1.4.2. Just update your gulp-sassvg module and it should work!
