### ISSUE TITLE
hello , thanks for your service but i have a quesition

### ISSUE THREAD

**Issue by wjddnr316** [MattDiMu/gulp-sassvg#20]
Thank you very much for creating such a useful library. However, I have a question. Why is UTF-8 character set not used? If it can be improved, I would appreciate it if you could consider it. Can I make this request?

**Comment by MattDiMu** [comment]
Sorry, but I'm not sure what you mean by "UTF-8 character set not used". The generated data svg strings should support utf8. Please comment/reopen, if I misunderstood you.
