### ISSUE TITLE
Some parts of multi-color SVGs appear black

### ISSUE THREAD

**Issue by RWeigelt** [MattDiMu/gulp-sassvg#7]
With gulp-sassvg 1.5.0, some parts of a multi-color SVG may appear black, caused by a missing semicolon. The generated SVG of one icon (created in Illustrator) e.g. contained the following `<style>` block:

```html
<style type="text/css"> .st0{fill: #616161;} .st1{stroke: #8E8E8Estroke-miterlimit:10;} .st2{fill: #FFFFFF;} </style>
```

Note the missing semicolon in `#8E8E8Estroke-miterlimit:10;`

I seem to have fixed the problem by adding a semicolon in lines 77 and 79 of index.js:

```
76    if(type == 'fill'){
77        out = 'fill: #{if($fillcolor, $fillcolor, ' + val + ')};'; // Added ; behind "}"
78    }else if(type == 'stroke'){
79        out = 'stroke: #{if($strokecolor, $strokecolor, ' + val + ')};'; // Added ";" behind "}"
80    }
```

I haven't tested this thoroughly, though ("works on my machine"), so I need some more time before an "official" pull request - which I haven't ever created before (I'll have to read up on that). So maybe it's faster if you look into this.

**Comment by MattDiMu** [comment]
Thx for the report. As far as I've seen this issue has been fixed in the latest rework to v3.0
